### ISSUE TITLE
Failed building BayesANT classifier

### ISSUE THREAD

**Issue by Changwanseo** [alessandrozito/BayesANT#2]
Hello. I tried to build BayesANT classifier with my custom data and it failed with 

```
Welcome to BayesANT 🐜 🐜 🐜 🐜  
No missing annotations detected. 
Estimating the Pitman-Yor parameters: Now. 
Estimating the Pitman-Yor parameters: Done. 
Computing prior probabilities: Now 
Computing prior probabilities: Done. 
Extracting kmers from sequences: Now. 
Extracting kmers from sequences: Done. 
Tuning hyperparameters: Now. 
Tuning hyperparameters: Done. 
Aggregating parameters: Now 
Error in hyperparameters[[index_prior]] : 
  recursive indexing failed at level 2
```

The code I used for running is
```
file.train <- ("008_bayesANT_input/Aspergillus_BenA.fasta")
rank <- 7
rank_names <- c( "Phylum", "Class", "Order", "Family", "Genus", "Species")
data <- read.BayesANT.data(fasta.file = file.train, 
                           rank = rank, 
                           rank_names = rank_names)
set.seed(10)
classifier <- BayesANT(data = data,
                       typeseq = "not aligned", 
                       type_location = "single", 
                       newtaxa = TRUE,
                       verbose = TRUE)
```
The error occuring file is attatched (Run in unzipped form)
[Aspergillus_BenA.zip](https://github.com/alessandrozito/BayesANT/files/12191161/Aspergillus_BenA.zip)

The running system is R version 4.1.2, R studio, and Windows 10

Please ask me if you need anything else

**Comment by alessandrozito** [comment]
Hello! Thanks for your interest in the package and for spotting the bug.

It seems that when loading the data through the function ```read.BayesANT.data```, the package creates an extra level in the data with no annotations. You can see this by typing ``head(data)``. A quick solution is to set ``rank <- 6`` in the code you provided.

Please let me know if it works.

**Comment by Changwanseo** [comment]
It worked!  Thanks!
