### ISSUE TITLE
problem of using prediction

### ISSUE THREAD

**Issue by CaiWang0503** [alessandrozito/BayesANT#3]
- Hi,
- I am trying to use predict(), but it returns this Error: 
- Error in { : task 1 failed - "replacement has length zero". 
- 
- Idk how to fix it, could help? Thank you very much.
- the BayesANT model was finished without any Error.
- 
- here is the code I used:
- classifier <- BayesANT(data = data,
                       typeseq = "not aligned", 
                       type_location = "single", 
                       usegap = FALSE,
                       verbose = T)

dataBayesANT_test <- read.BayesANT.testDNA("otu97.fasta")
dataBayesANT_test[1]

# Annotate a test sequence
out <- predict(classifier, 
                 DNA = dataBayesANT_test[1], 
                 rho = 0.1, 
                 return_probs = FALSE)

Error in { : task 1 failed - "replacement has length zero"

**Comment by alessandrozito** [comment]
Hi! Thanks for your interest in BayesANT!

Can you please send me an example of data where this problem arises? I'll directly look into it. 

In the meantime, does the function fail also when you select typeseq = "aligned"? (assuming you have aligned sequences)

Ale

**Comment by CaiWang0503** [comment]
[testdata.zip](https://github.com/alessandrozito/BayesANT/files/14767060/testdata.zip)
thank you, here is the data and code, the sequence are not aligned.

**Comment by CaiWang0503** [comment]
Hi Ale,
I have solved that problem. I think the problem is because my reference database doesn't match my inquiring sequence (test dna), when I use a different reference dataset, the prediction function works. I close this issue. thank you.

**Comment by CaiWang0503** [comment]
Hi Ale,
I have solved this problem. I think the problem is that my reference database doesn't match my query sequence (test dna), when I use a different reference database, the prediction function works. I will close this issue, thank you.
